### ISSUE TITLE
Anyhow related to Watchgram for Apple Watch?

### ISSUE THREAD

**Issue by felipecrs** [cassian237/WatchGram#1]
Hi, I found your app when searching for Telegram in Play Store and bought a copy to support you. I haven't installed it yet though.

I would like to ask: is your app or you anyhow related to this Apple Watch app?

https://apps.apple.com/app/watchgram-for-telegram/id6508166906

**Comment by cassian237** [comment]
Hi, thank you so for your support and for purchasing my app! I truly appreciate it.

To answer your question, I am not affiliated with the Apple Watch app you mentioned. I was not aware of that app before choosing the name “Watchgram for Telegram” for mine. Any similarity in names is purely coincidental.

**Comment by felipecrs** [comment]
Understood, thank you!
